#!/bin/bash

echo "Creanting openshift wsgi dir"
mkdir -p wsgi

echo "Making symbolic links"
ln -ns siade/wsgi.py wsgi/application
ln -ns static wsgi/static

echo "Executing 'python $OPENSHIFT_REPO_DIR/wsgi/openshift/manage.py migrate --noinput'"
python "$OPENSHIFT_REPO_DIR"wsgi/openshift/manage.py migrate --noinput
