#!/bin/bash

echo "Creanting openshift wsgi dir"
mkdir -p "$OPENSHIFT_REPO_DIR"/wsgi

echo "Making symbolic links"
cp "$OPENSHIFT_REPO_DIR"/siade/wsgi.py "$OPENSHIFT_REPO_DIR"/wsgi/application

echo "Executing 'python $OPENSHIFT_REPO_DIR/wsgi/openshift/manage.py collectstatic --noinput'"
python "$OPENSHIFT_REPO_DIR"/manage.py collectstatic --noinput

echo "Executing 'python $OPENSHIFT_REPO_DIR/wsgi/openshift/manage.py migrate --noinput'"
python "$OPENSHIFT_REPO_DIR"/manage.py migrate --noinput
