language: python
python:
- '2.7'
install:
  - apt-get install python-mysqldb
  - pip install -r requirements.txt
before_script:
  - mysql -e 'create database siade_test;'
env:
  global:
  - DJANGO_SETTINGS_MODULE=siade.settings.test
  - TEST_DB_NAME=siade_test
  - TEST_DB_USER=travis
script: python manage.py test
branches:
  only:
  - master
deploy:
  provider: openshift
  user: roldaojr
  password:
    secure: QFVDG4WIBRTNfx0GVwoNom6LxR2nZISl5ikuCfTjwiDUV+kI9IXh9Zj2834MT3/O+6y+XawUk/74HRDHjNK3/MStNJIrbdlomynZFO9xDknfu07F+tk7StGg/Ou59JyvEz/5QzWfNVCoggCw0VYjUcBTKE4A1ZS25EfyxUsftW0=
  app: siade-server
  domain: rgj
  on:
    repo: holocronifrn/siade-server
