language: python
python:
  - "2.7"
install: "pip install -r requirements.txt"
before_script:
  - mysql -e 'create database siade_test;'
env:
  - DJANGO_SETTINGS_MODULE=siade.settings.test
  - TEST_DB_NAME=siade_test
  - TEST_DB_HOST=127.0.0.1
  - TEST_DB_PORT=3306
  - TEST_DB_USER=travis
  - TEST_DB_PASS=
script: "python manage.py test"
branches:
  only:
    - master