# -*- coding: utf-8 -*-
from siade.imoveis.models import *

ruas = (
'Avenida Getúlio Vargas',
'Avenida da Independência',
'Rua 15 de Novembro',
'Rua 13 de Maio',
'Rua 07 de Setembro',
'Rua Dom Pedro II',
'Rua Pedro Velho',
'Rua Francisco Marçal',
'Rua Bevenuto Fialho',
'Rua Tabelião José Tomáz',
'Rua João de Aquino',
'Rua Honorato Lopes',
'Rua Antístenes Diógenes',
'Rua Álvaro de Andrade',
'Rua Sebastião Dias',
'Rua Mano Marcelino',
'Rua João Escolástico',
'Rua Manoel Aires',
'Rua Quintino Bocaiúva',
'Rua Adolfo Fernandes',
'Travessa Jessé Pinto Freire',
'Travessa Tércia M. Dutra',
'Travessa Teófilo Rego',
'Travessa Amaro Cavalcante',
'Travessa Diva Holanda',
'Rua 25 de Março',
'Rua Cícero Feitosa da Silva',
'Rua Lindolfo Noronha',
'Rua Teresinha Francisca de Jesus',
'Rua José Romualdo de Paiva',
'Rua Antonio Laurino',
'Rua Severino Rego',
'Rua José Florêncio',
'Rua Leudes Chaves de Aquino',
'Rua Cônego Manoel Caminha Freire',
'Rua Otávio de Souza Rego',
'Rua Vereador Antonio Barros',
'Rua Fausta Patrícia Rego Fernandes',
'Rua Francisca Lopes Cavalcante',
'Rua Omar de Freitas',
'Rua  Lucas Batalha',
'Rua José Alves de Queiroz',
'Rua Olavo Diógenes',
'Rua Mainha Diógenes',
'Rua  Francisca das Chagas de Almeida',
'Rua dos Jarmins',
'Rua das Lavandas',
'Rua das Peônias',
'Rua dos Amarílis',
'Rua dos Crisântemos',
'Rua das Hortências',
'Rua das Rosas Amélias',
'Rua das Violetas',
'Rua das Orquídeas',
'Rua das Margaridas',
'Rua Francisco Fernandes França',
'Rua Alexandre Fernandes da Silveira Neto',
'Rua Professor José Nilson Feitosa',
'Rua Manoel Teixeira da Silva',
'Rua José Bessa Filho',
'Rua Joaquim Pedro da Silva',
'Rua Pedro César Texeira da Silva',
'Rua João Tomás da Silva',
'Rua José Gilberto Barreto',
'Rua Doninha Melo',
'Rua  Maria Lenilda Brasil',
'Rua Clidenor Régis de Melo',
'Rua Cícera Vidal da Costa',
'Rua Francisco Diógenes Pessoa',
'Rua Raimundo Vieira da Silva',
'Rua Amália Régis de Melo',
'Rua Alaíde Diígenes Bessa',
'Rua Raimundo Mariano de Melo',
'Rua Querubina Maria da Conceição',
'Rua Manoel Abílio de Oliveira',
'Rua Ubaldina Diógenes Dantas',
'Rua Maria Zecilda Porto Diógenes',
'Rua Antonieta Germano',
'Rua Nelson Maia',
'Rua Eliezer Joca Feitosa',
'Rua Maria Dália da Silveira',
'Rua Firmino Vidal',
'Rua Gabriel Antonio Chaves',
'Rua Francisco Abílio de Oliveira',
'Rua Margarida Maria Fernandes',
'Rua Maria Taveira Bessa',
'Rua Antonio Fernandes de Aquino',
'Rua Francisco de Paula Fernandes (Chico de Paula)',
'Rua Maria José Holanda',
'Rua José Bezerra ( Zé Vidal)',
'Rua Aluízio Holanda da Costa',
'Rua Sargento Moacir ',
'Rua João Felix de Lima ( Lima Soldado)',
'Rua Jader de Holanda Cavalcante',
'Rua Sargento Guido',
'Rua Chico Torquato',
'Rua Professora Verônica de Assis',
'Rua Chico de Dulce',
'Rua Vereador Heronildes Raulino de Queiroz',
'Rua Cleônio Otaviano Almeida Souza',
'Rua  Antonio Leite Dias',
'Rua Carlos Rubens do Nascimento',
'Rua Josefa Esmeraldina do Rego',
'Rua João Avelino do Nascimento',
'Rua Pastor Siqueira',
'Avenida  Desembargador Hemetério Fernandes ',
'Rua Afonso Silva',
'Rua Palmira Chaves de Oliveira',
'Rua Cícero Almino de Souza',
'Rua Israel Martins do Nascimento',
'Rua José Fernandes do Rego',
'Rua Tedinho Freitas',
'Rua Cosme Lopes de Silva',
'Rua Manoel Justino da Costa',
'Rua Auta Rego',
'Rua Ozório Augusto de Oliveira',
'Rua Severino Limão de Souza',
'Rua Antonio Alves Pereira',
'Rua Ricarte Crescêncio Batalha',
'Rua José E. Feitoza  ',
'Rua José Elpídio do Rego',
'Rua Gentil Estevam do Rego',
'Rua Sargento Toinho',
'Rua Antonio de Castro Feitosa',
'Rua Abdon Pinheiro de Araújo',
'Rua Manoel Fulô',
'Rua Francisco Xavier de Castro',
'Rua Vicente Barros da Silva',
'Rua Maria do Carmo Gurgel',
'Rua Maria Lildete Rodrigues da Costa',
'Rua Maria Bezerra de Freitas',
'Rua Dr. Rafael Fernandes',
'Rua Maria das Graças Gameleira',
'Rua José Ademar do Nascimento',
'Rua João Augusto Maia',
'Rua Raimunda Alves da Silva',
'Rua Zé Lampião',
'Rua Ana Moreira do Rêgo',
'Rua Francisco de Castro Jucá',
'Rua Amâncio Faustino da Silva',
'Rua Antonio Pedro da Silva',
'Rua José Gameleira Sobrinho',
'Rua Cícero Salvador',
'Rua Raimundo Maria',
'Rua Zé das Cavas',
'Rua Nonato vaqueiro',
'Rua José Galdino do Rego',
'Rua Hemetério Gameleira do Rego',
'Rua Dr. Galdino Bisneto dos Santos Lima',
'Rua Francisco Raulino da Costa',
'Rua Elias de Sousa Feitosa',
'Rua Joana de Castro Feitosa',
'Rua Honorato de Souza Rego',
'Rua Alberto Barbosa de Miranda',
'Rua Itamar Dutra de Oliveira',
'Rua Raimundo Fernandes Neto',
'Rua Laurino Alexandre da Costa',
'Rua José Elias de Freitas',
'Rua Maria Luzia de Almeida',
'Rua Francisco Torquato do Rego',
'Rua Vereador Antonio Izidio',
'Rua José Paulino do Rego',
'Rua Antonio Alves de Queiroz',
'Rua Manoel Quintino do Rego',
'Rua José Nizário Vidal de Queiroz',
'Rua Manoel de Brito',
'Rua José Cecílio Neto ( Zé Coca)',
'Rua Renato Almeida Barros',
'Rua Antonio Pessoa de Queiroz ',
'Rua Antonio Alves da Costa',
'Rua José Gameleira Filho',
'Rua Francisco Correia de Lima',
'Rua Manoel Sebastião de Araújo',
'Rua Geraldo Diógenes',
'Rua Deputado Antonio Florêncio de Queiroz',
'Rua Antonio Elias Feitosa',
'Rua Maria Dulce',
'Rua Expedito Pinheiro',
'Rua Dr. Pedro Diógenes Júnior',
'Rua Vereador Agábio Diógenes Pessoa',
'Rua Cristina Diógenes Nunes',
'Rua Alzira Diógenes Fernandes',
'Rua Luiz Gonzaga de Morais',
'Rua Frei Damião de Bozano',
'Rua Presidente Jânio Quadros',
'Rua Pedro Elias Feitosa',
'Rua João Francisco do Nascimento',
'Rua Profº. José Alves de Souza',
'Rua Pedro Pierre dos Santos',
'Rua Maria Fiel de Souza',
'Rua Ilda Alves de Sena',
'Rua Vereador Antonio Chaves',
'Travessa  Braulino Cabral',
'Travessa José Benevides de Aquino',
'Rua  Creuza Maria',
'Rua Maria Antonia Dias de Oliveira',
'Rua Antonio Gameleira do Rego',
'Rua Eliseu Pessoa de Queiroz',
'Rua Benedito Fernandes Sampaio',
'Rua Águida Maria de Queiroz',
'Rua Monsenhor Walfredo Gurgel',
'Rua Francisco Lopes Rego (Chico de Regina)',
'Rua Maria das Dores de Queiroz',
'Rua Genival de Souza',
'Rua Joel Praxedes',
'Rua Antonio Lopes',
'Rua Francisco do Rego Leite',
'Rua Glicério de Souza',
'Rua José Gualberto de Souza',
'Rua Vereador Gonçalo Sampaio',
'Rua Francisca de Castro',
'Rua Maria Edite',
'Rua Maria Simão',
'Rua Cícero Angelino de Araújo',
'Rua Augusta França de Souza',
'Rua Maria Baiquinha de França',
'Rua Josefa Maria do Rego',
'Rua Chico de Róseo',
'Rua Benedito Miguel dos Santos',
'Rua Músico Antonio Muqueca',
'Rua Honor Lopes Chaves',
'Rua Chico Lima',
'Rua Marcina Januária de França (Dona Marcina)',
'Rua Manoel Bandeira',
'Rua Adelino Aires',
'Rua Antonia Taveira Bessa',
'Rua  Rafael Fernandes de Queiroz',
'Rua Pedro Pernambuco',
'Rua Sérgio Pessoa',
'Rua Maria Severiana do Rego',
'Rua Manoel Rosa de Andrade',
'Rua Vereador Tinô Rego',
'Rua  Urbano Fernandes de Melo',
'Rua  Edite Lopes do Rego',
'Rua Maria Diva Nogueira',
'Rua  Benedito Fernandes Sampaio',
'Rua João Pereira do Nascimento',
'Rua Idalina Nogueira	',
'Avenida Terra do Sol',
'Rua Josemar Lopes Sampaio',
'Rua Pedro Elias Sobrinho (Pedrinho do Padre)',
'Rua Joana Regis de Melo',
'Rua Antonia Guedes do Rego',
'Rua José Alves de Oliveira (Zé Aureliano)',
'Rua João Cristovam Torres',
'Rua Antonio Vidal da Costa',
'Rua Felipe Neres Fernandes',
'Rua Luiz Nogueira de Lima',
'Rua  João Henrique da Cunha',
'Rua  Antonio Dóia Neto',
'Rua Erico Luiz Souza do Rego',
'Rua Raimundo Peixoto de Queiroz',
'Rua Anízio Lopes da Silva (Anizio Borges)',
'Rua Francisco Francelino (Chico do Brabo)',
'Rua Luiz Pereira do Rego',
'Rua Eleni Bezerra Fernandes',
'Rua Alcídes José do Nascimento',
'Rua Adauto Fernandes de Queiroz',
'Rua Henrique Barbosa de Amorim',
'Rua Francisco Alexandre de Holanda',
'Rua Avelino Ferreira da Silva Guedes',
'Rua José Alves Rodrigues',
'Rua Valdir Lopes Chaves',
'Rua Maurício Florêncio de Queiroz',
'Rua Quinho Aires',
'Rua Pedro França de Souza',
'Rua José Soares da Silva',
'Rua Regina de Souza Rego',
'Rua Simão Cirineu',
'Rua Antonio Gurjão',
'Rua Capitão Pedro Vicente',
'Rua Raimundo Maia',
'Rua Firmina Guedes do Rego',
'Rua João Bezerra de Queiroz',
'Rua Itamiran Nunes de Aquino Lima',
'Rua Zé  Sátiro	',
'Rua Vicente José de Queiroz',
'Rua Narla Nayara Duarte Batista',
'Rua Professora Maria Lúcia de Aquino Chaves',
'Rua Maria Bezerra da Rocha',
'Rua São Benedito',
'Rua São João',
'Rua São Manoel',
'Rua Donaciano Cavalcante',
'Rua Vereador Mauri Lira',
'Rua Paul Harris',
'Rua José de Holanda Pinto',
'Rua Francisco Henrique da Cunha',
'Rua Fransualdo Pereira de Lima',
'Rua João de Oliveira Pessoa (Trav. São Manoel)',
'Rua Antonio Januário',
'Rua Maria Fernandes de Aquino',
'Rua Cícero Trajano',
'Rua Canindé de Noête',
'Rua Francisco Sales de Aquino',
'Rua Nezinho Batista',
'Rua Carloto Távora',
'Avenida Senador Dinarte Mariz',
'Rua Antonio Neto de Souza',
'Rua Francisco Gameleira',
'Rua Dandão Sena',
'Rua Maria Silva de Lima',
'Rua Lilia do Padre',
'Rua José de Holanda',
'Rua da Criança',
'Rua Raimundo Melo de Oliveira',
'Rua Emília Gameleira do Rego',
'Rua Jonas Noronha',
'Rua Toinha Caraúba',
'Rua Eleutério Fernandes de Queiroz',
'Rua Inácio Lopes',
'Rua Cosme Elias',
'Rua Francisco Monteiro de Oliveira',
'Rua Joaquim Correia Filho',
'Rua José Caju',
'Rua Cícero Alberto de Morais',
'Rua Raimundo Marcelino Fernandes',
'Rua José Francisco de Lucena',
'Rua Terezinha Queiroz',
'Rua Tertuliano Sinfrônio de Queiroz',
'Rua Zeferino Ferreira Vilaça',
'Rua José Estevão do Rego',
'Rua Gilberto Pinheiro de Morais',
'Rua Dr. Jaime de Aquino',
'Rua Francisco Dantas',
'Rua Napoleão Diógenes	',
'Rua Lafaiete Diógenes',
'Rua São Francisco',
'Rua Hipólito Cassiano',
'Travessa Isaura Aquino',
'Travessa Joaquim de Holanda',
'Travessa Soldado Raimundo Lacrau ',
'Vila Elianto Pignataro (DNOCS)',
'Rua Frei Galvão',
'Rua Pedro Lopes Chaves',
'Rua Luiz França Maia',
'Rua Soldado José Américo',
'Rua Joaquim Torquato',
'Rua Antonio Inácio',
'Rua Cosme Januário de Aquino',
'Rua Bernardo Pessoa de Queiroz',
'Rua Horácio Bernardino de Sena',
'Rua Seu Badú',
'Rua Raimundo do Padre',
'Rua João de Madalena',
'Rua Amélia Pessoa de Queiroz',
'Rua Celso José de Queiroz',
'Rua João Vidal Bezerra (João Biró)',
'Rua Vereador Gaudêncio Jerônimo de Souza ',
'Rua Auto Garcia Dantas	',
'Rua Mariana Guedes do Rego',
'Rua Sebastião Lucas da Mota',
'Rua Vereador João Queiroz de Souza',
'Rua Professora Zita Fernandes',
'Rua Professora Maria Margarida de Queiroz',
'Rua José Estácio do Nascimento',
'Rua João Benevides de Aquino',
'Rua Maria Gorete Batista Henrique',
'Rua Francisco Alves Holanda (Poroca)',
'Rua Seu Cazuzinha',
'Avenida Joana Fernandes de Bessa',
'Rua Raimundo Caldas de Oliveira',
'Rua Santina Araújo de Souza',
'Rua Jacira de Souza Sena',
'Rua Terezinha Fernandes Nogueira',
'Rua Deco Morais',
'Rua José Aldaécio Chagas de Oliveira',
'Rua João Balbino de Queiroz',
'Rua José Elói Filho (seu Dedeca)',
'Rua Toinho Joca',
'Rua José Agostinho Simão',
'Rua Alexandre Canuto de Souza',
'Rua Honorato Augusto de Oliveira',
'Rua Acelino Severino da Costa',
'Avenida Joaquim Lopes Cardoso',
'Rua Matilde Sampaio de Queiroz',
'Rua Manoel Henrique da Cunha',
'Rua Agnelo Peixoto de Queiroz',
'Rua Henrique Neto da Cunha',
'Rua Miguel Correia de Queiroz',
'Rua Soldado Xaxú',
'Rua Marcos Santos de Araújo',
'Rua Inácio Pereira da Silva',
'Rua Conrado Henrique Sobrinho',
'Rua Ari Rodrigues Maia',
'Rua Maria Madalena de Jesus',
'Rua Joana Monteiro da Silva',
'Rua Dom Helder Câmara',
'Rua José Simão de Araújo',
'Rua Aristide Pereira da Silva',
'Rua Joana Maria do Espírito Santo',
'Rua Mãe Cristina',
'Rua Ernestina Araújo de Souza',
'Rua Irmã Ana Maria Rafael',
'Rua Damázio Francisco do Nascimento',
'Rua Misael Bezerra de Queiroz',
'Rua Walter Correia de Aquino',
'Rua José Gomes de Morais',
'Rua Cabo José Dantas',
'Rua Francisco Damião da Silva',
'Rua Oton José de Queiroz',
'Rua Profª Elienita Pontes',
'Rua Severino de Freitas Rego',
'Rua Mauricio Rego',
'Rua Prof. Magnaldo',
'Rua Juiz João Vicente da Costa',
'Rua José Severino da Silva',
'Rua  Antonio Lisboa Avelino',
'Rua  João Rodrigues de Oliveira',
'Rua  Raimundo Nonato de Oliveira',
'Rua Maestro Wilson Arnoud',
'Rua José Diógenes Maia	',
'Rua Ari Alves da Silva',
'Rua João Chaves',
'Rua Augusto Barbosa de Sales',
'Rua Paulo Soldado',
'Rua Antenor Maia de Lima',
'Rua José Edílson Freire de Carvalho',
'Rua Francisco Floriano Ferreira',
'Avenida Uriel Fernandes da Silveira',
'Rua José Avelino do Nascimento',
'Rua João Gualberto do Rego',
'Rua General André Fernandes',
'Rua Desembargador Licurgo Nunes',
'Rua Francisco França de Souza',
'Rua Deputado Israel Nunes',
'Rua José Ferreira da Costa',
'Rua Vicente Fernandes',
'Rua Antonio Franco de Oliveira',
'Avenida Estados Unidos',
'Avenida Brasil',
'Rua Espanha',
'Rua Portugal',
'Rua Nova Zelândia',
'Rua Canadá',
'Rua Vereador Adauto Dantas Lins',
'Rua França',
'Rua Inglaterra',
'Rua Austrália',
'Rua Israel',
'Rua Costa Rica',
'Rua Chile',
'Rua Suiça',
'Rua Egito',
'Rua Marrocos',
'Rua Paulo Marcelino',
'Rua Maria Selma de Assis',
'Rua Raimundo S. Nunes',
'Rua Agostinho F. Queiroz',
'Rua Antonio Alexandre',
'Rua Djalma de Freitas',
'Rua Raimundo S. do Rego',
'Rua Lavoisier Lamarck Bezerra',
'Rua Higino J. Bezerra',
'Rua Manoel de Castro',
'Rua Respício José do Nascimento',
'Rua João Batalha',
'Rua Dr. Raimundo Diógenes S. Paiva',
'Rua Hermógenes S. do Rego',
'Rua Pedro Régis de Freitas',
'Rua José Correia',
'Rua Manoel Antonio',
'Rua Dr. José Torquato',
'Rua Balduíno José do Nascimento',
'Rua Francisco A. de Queiroz',
'Rua Antonio A. de Souza',
'Rua Francisco de A. Rêgo',
'Rua Dr. Elias Fernandes',
'Rua Manoel Gameleira',
'Rua Cícero Estevão',
'Rua Ananias Aires',
'Rua Francisco Batalha',
'Rua Alexandre Pinto',
'Rua Sérvulo Fernandes Pimenta',
'Rua Véscio Torquato',
'Rua Gaudêncio Torquato',
'Rua José Meireles Ponchet',
'Rua Francisca Lopes Bezerra',
'Rua Celí Pinheiro Lobo',
'Rua Estevam Romão França',
'Rua Antonio de Lisboa Lopes',
'Rua Manoel Alexandre',
'Rua Marta Neta de Almeida Souza',
'Avenida Ubiranilton Deodato',
'Rua Antonio Torzinho Pinheiro',
'Rua Valdemar Miranda de Freitas',
'Rua Aprides Deodato',
'Rua Hilda Maria de Freitas',
'Rua José Miranda',
'Rua Francisco Amadeu Leite ',
'Rua Euclídes Queiroz',
'Rua Maria Torquato de Freitas',
'Rua Francisco Alexandre Nunes',
'Rua Zé Vaqueiro',
'Rua Elias Feitosa de Castro',
'Rua Leonel Gonçalves Dantas',
'Rua Alderico Batista de Araújo',
'Rua Francisco Lopes Filho (Tiquinho de Balau)',
'Rua Antonio Fernandes do Rego',
'Rua Rita Santina da Costa',
'Rua Luiza Campelo de Moura',
'Rua Apolônia Apoloniza de Morais',
'Rua Maria Augusta Collares',
'Rua José Ferreira',
'Rua João Raulino da Costa ',
'Avenida Vingt Rosado',
'Avenida Dr. Nelson Maia',
'Avenida José Raulino da Costa',
'Rua Rota do Sol Dr. Nilton Figueiredo',
'Rua Severino Vieira Torres',
'Rua Fransquinha Alves',
'Rua Manoel Lopes Bandeira',
'Rua Maria José Dantas',
'Travessa Manoel Bento da Silva',
)

bairros = (
'Chico Cajá',
'São Vicente de Paula',
'Frei Damião',
'São Judas Tadeu',
'Paraíso',
'João XXIII',
'São Benedito',
'Riacho do Meio',
'São Geraldo',
'Domingos Gameleira',
'Zeca Pedro',
'João Catingueira',
'Aluísio Diógenes Pessoa',
'Alto do Açude',
'Bela Vista',
'Manoel Domingos',
'Princesinha Do Oeste',
'Nações Unidas',
'Manoel Deodato',
'Arizona',
'Carvão',
	)


def carregar_bairros():
	u, c = UF.objects.get_or_create(nome='Rio Grande do Norte', sigla='RN')
	m, c = Municipio.objects.get_or_create(nome='Pau dos Ferros', codigo='100', uf=u)
	for model in bairros:
		Bairro.objects.get_or_create(municipio=m, nome=model)


def carregar_ruas():

	m = Municipio.objects.get(nome='Pau dos Ferros')
	for model in ruas:
		Logradouro.objects.get_or_create(municipio=m, nome=model)

def run():
	carregar_bairros()
	carregar_ruas()